### ISSUE TITLE
تداخل الحروف مع بعضها البعض في قاريء الكتب kobo 

### ISSUE THREAD

**Issue by asaif** [khaledhosny/amiri-font#226]
عند أستخدام الخط الأميري في قاريء الكتب الإلكتروني كوبو kobo libra 2 
تتداخل الحروف مع بعضها البعض آحيانا بشكل يصعب قرائته 
مرفق صوره للتداخل 

![image](https://user-images.githubusercontent.com/192287/144035059-a973f287-7959-42f5-bd87-6779d1328390.png)

**Comment by khaledhosny** [comment]
لا أظن أن هذه مشكلة في الخط، يبدو عيبا في البرنامج المستخدم.

**Comment by khaledhosny** [comment]
أظن أن البرنامج يطبق ضبط المسافات بين الحروف (kerning) خطأ.
