### ISSUE TITLE
الفتحة لا توضح فوق الهمزة (U654)

### ISSUE THREAD

**Issue by hubaishan** [khaledhosny/amiri-font#227]
الخط الأميري متميز بأن الهمزة توصل ما قبلها بما بعدها عند إمكانية الوصل مما يتيح كتابة الرسم العثماني بأريحية، بخلاف بقية الخطوط التي تفصل الكلمة، لكن الإشكالية عند العرض في الويب والرغبة في عمل نص متوافق مع بقية الخطوط في حالة عدم توفر الخط الأميري فإن الحل في استعمال الكشيدة ثم الهمزة فوقها  (U654) ثم الشكلة إذا كانت فتحة أو ضمة وهذا الرسم متوافق مع بقية الخطوط سوى الخط الأميري 
فإنه يضع الفتحة على الكشيدة والهمزة بعدها
فسـَٔل
![image](https://user-images.githubusercontent.com/2285457/144188666-54dba354-408d-473a-8af9-9fb664e018cf.png)

**Comment by khaledhosny** [comment]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/93914/144227885-84ce2f5b-a3d9-49f0-b764-a7c6ae53c837.png">
