### ISSUE TITLE
خلل في النسخة الجديدة من خط Amiri Quran مع الوورد

### ISSUE THREAD

**Issue by hubaishan** [khaledhosny/amiri-font#228]
النسخة الأخيرة من   Amiri Quran من الفرع main والمعدلة في 4-12-2021   غير متوافقة مع برنامج مايكروسوفت  وررد وبرنامج الدفتر في ويندوز

ويظهر الخلل عند اۤ الألف التي عليها مدة
مرفق صورة 
![image](https://user-images.githubusercontent.com/2285457/149921166-cfbb5057-9686-40ba-bc81-062f34cffbd5.png)
نفس النص بالأعلى خط Amiri وبالأسفل  Amiri Quran وورد 2010
![image](https://user-images.githubusercontent.com/2285457/149921372-ae1d8fbb-71d7-4147-9aff-1ca17449461d.png)
برنامج الدفتر نسخة ويندوز 10

**Comment by khaledhosny** [comment]
تحدث هذه المشاكل مع محركات خطوط وندوز من حین لآخر، ولا سبیل لی لمعرفة مصدرها. إذا أمكنك تحدید التغییر الذی ظهرت بسببه المشكلة، قد أستطیع أن أجد حلا لها، أما بدون ذلك فلا أعرف حتى أین أبحث.

**Comment by hubaishan** [comment]
جربت أغلب نسخ otf كلها فيها خلل  وذلك من النسخ الصادرة بعد 0.113
ويظهر الخلل في بعض التركيبات التي تلغي كل الكتابة السابقة لها في نفس السطر مثل الألف الخنجرية فوق المسافة غير المنقسمة والمدة فوق الألف
نسخ ttf القديمة سليمة

**Comment by khaledhosny** [comment]
إذا كنت تستخدم git فیمكنك استخدام أمر git bisect لتحديد التغییر الذی بدأت عنده المشكلة.

**Comment by hubaishan** [comment]
هل يمكن إنشاء نسخ ttf من الخطوط من فرع mian؟ وكيف؟

**Comment by khaledhosny** [comment]
باستخدام `make ttf`

**Comment by khaledhosny** [comment]
ملفات TTF موجودة فی المستودع الآن.

**Comment by hubaishan** [comment]
الحمد لله النسخة الأخيرة سليمة
