### ISSUE TITLE
Positioning of U+0650 kasra under U+0671 Alef Wasla

### ISSUE THREAD

**Issue by adamiturabi** [khaledhosny/amiri-font#230]
Similar to issue #186 

The positioning of U+0650 kasra under U+0671 Alef Wasla may need to be fixed; it is far too low and not centered:
![image](https://user-images.githubusercontent.com/61895563/151742915-90f7e778-1717-497b-ae51-ace656065a42.png)

Thank you!

**Comment by khaledhosny** [comment]
Works fine here, what version of the font are you using and what application?

![](https://user-images.githubusercontent.com/93914/157230734-3ce2eb0c-e9f2-41ba-b6ba-d1bcaebdfb83.png)
