### ISSUE TITLE
Kashida overlapping issue - Amiri font

### ISSUE THREAD

**Issue by nidakhan** [khaledhosny/amiri-font#231]
Hi! Issue I'm experiencing with your font Amiri. It shows up fine when I paste and preview text in Google Font, but not when I use Amiri and try and typeset in Illustrator or Indesign. The two kashidas overlap. See image, I've put a red box around it
![CleanShot 2022-03-21 at 20 03 48@2x](https://user-images.githubusercontent.com/831089/159382345-19ce838d-731e-4188-b247-052d8a73a4fa.jpg)
.

**Comment by khaledhosny** [comment]
The input text seems to have been subject to Unicode normalization which would put the fatha before the shadda. Some applications know to handle this, but apparently these two Adobe apps don’t. The simplest fix is to retype this part and enter the shadda first then the fatha.
