### ISSUE TITLE
اقتراح بإضافة

### ISSUE THREAD

**Issue by hatemibrahim1410** [khaledhosny/amiri-font#233]
السلام عليكم، 
جزاكم الله خيرًا على هذا الجهد القيم وهذه المتابعة لتطوير الخط المتميز.

إن أمكن إضافة حزمة للخط الأميري يكون في بشكل ثابت خط علوي فوق الكلمات (Over line) ، إذ هذا الخيار غير متاح بشكل ميسور في برامج (Office) عمومًا، وحتى عن تطبيق الاقتراحات لا تسعف في إتمام الخط العلوي على الوجه المطلوب الميسور كما يكون في خيار (Under Line).

بالتوفيق لكل خير، وجزاكم الله خيرًا.

**Comment by khaledhosny** [comment]
یمكن استخدام علامة السطر العلوی (U+0305) فالخط الأمیری یدعمها لإعطاء سطر علوی متصل:
> یَ̅سۡ̅جُ̅دُ̅و̅نَ̅ 

<img width="203" alt="image" src="https://user-images.githubusercontent.com/93914/164997505-93800323-76e2-4969-a7b8-996a2837e162.png">

**Comment by khaledhosny** [comment]
أضفت الدعم إلى كل الخطوط ولیس خط القرآن فقط:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/93914/164998280-26c34106-29ac-4ae0-81b5-0b3f810cb068.png">

**Comment by hatemibrahim1410** [comment]
شاكر جدًا لحضرتك هذا الحرص، وهذه المتابعة.
لكن يرجى توضيح طريقة مصورة لإثبات الخط على الكلمات !!

**Comment by hatemibrahim1410** [comment]
هذه صورة لما حاولت نقل النص إلى (مايكروسوفت أوفيس):
![Screenshot_1](https://user-images.githubusercontent.com/71362757/164998937-c05e3a4e-98ac-4908-8e9c-cc74d80c77db.png)

**Comment by khaledhosny** [comment]
من الصورة يظهر أنك تستخدم نسخة قديمة من الخط، أقترح أن تحذف النسخة القديمة وتنزل النسخة الجديدة (في النسخة الجديدة السطر فوق علامات التشكيل): بالذهاب إلى https://github.com/aliftype/amiri/blob/main/Amiri-Regular.ttf وتنزيل الملف.

**Comment by hatemibrahim1410** [comment]
شاكر لحضرتك، إن شاء الله أستخدم النسخة الأحدث، وأتابع مع حضرتك...
