### ISSUE TITLE
Kashida 

### ISSUE THREAD

**Issue by tommai4881** [khaledhosny/amiri-font#235]

**Comment by khaledhosny** [comment]
?

**Comment by tommai4881** [comment]
Your font should support kashida as in other arabic fonts, I’ve seen
Scheherazade New font support Kashida well

**Comment by khaledhosny** [comment]
It does support Kashida. Please elaborate on the issue you have.

**Comment by tommai4881** [comment]
Yea, it doesnt kashida properly as in other fonts
