### ISSUE TITLE
مشكلة في التشكيل

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#239]
الخط جميل جدًا ولكن لا يدعم الشدة المكسورة حيث تكون الشدة فوق والكسرة تحت بينما في العادي يكون الأثنان فوق أرجو حل المشكلة

**Comment by khaledhosny** [comment]
يمكنك استخدام خاصية  `ss05`، راجع [توثيق الخط](https://www.amirifont.org/documentation/Documentation-Arabic.html#%D8%A7%D9%84%D8%AE%D8%B5%D8%A7%D8%A6%D8%B5-%D8%A7%D9%84%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%DB%8C%D8%A9).

**Comment by Mos6720009** [comment]
كيف أفعل تلك الخاصية

**Comment by khaledhosny** [comment]
ما البرنامج الذي تستخدم الخط فيه؟

**Comment by Mos6720009** [comment]
برنامج مايكروسوفت وورد

**Comment by khaledhosny** [comment]
تتبع الخطوات كما في هذا الشرح https://www.macworld.com/article/227757/how-to-access-advanced-opentype-features-in-a-variety-of-mac-apps.html#using-microsoft-word

**Comment by Mos6720009** [comment]
أيمكنك أعطاني طريقة اسهل أو قم بعمل تعديل على الخط

**Comment by khaledhosny** [comment]
لا أرى ما الصعوبة في هذه الطريقة.

**Comment by Mos6720009** [comment]
ولكن هل اوبن تايب برنامج أم أن هناك برنامج يدعمه

**Comment by khaledhosny** [comment]
أوبن تيب هو نوع ملفات الخطوط، وملفات الخط الأميري من هذا النوع.

**Comment by Mos6720009** [comment]
أيمكنك أعطائي برامج لأصلاح مشكلة الشدة المكسورة

**Comment by Mos6720009** [comment]
آسف لأتعابك معي جربت الطريقة التي في الرابط وراجعت توثيق الخط أتمنى أن تستمر في تحديث وتحسين الخط شكرًا لك

**Comment by khaledhosny** [comment]
العفو.

هل عملت معك هذه الطريقة؟

**Comment by Mos6720009** [comment]
أجل

**Comment by khaledhosny** [comment]
عظيم
