### ISSUE TITLE
اقتراحات لأضافتها في التحديث القادم

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#241]
السلام عليكم أتمنى إضافة نفس اللام الخاصة بالجهل في الصورة و ارجوك لا تغلق الرسالة لأني لو وجدت اقتراحات سوف اضيفها مستقبلا والسلام عليكم
![Screenshot_٢٠٢٢٠٩١١-١٧٥٦٠٨_Google](https://user-images.githubusercontent.com/112905893/189537387-26bed5f6-e121-43bc-9f0d-574f8fa06979.jpg)

**Comment by Mos6720009** [comment]
لماذا لم ترد

**Comment by khaledhosny** [comment]
ما فائدة هذه الإضافة؟

**Comment by Mos6720009** [comment]
مثلا لو كنت تريد كتابة كلمة فيها لح أو لخ او لج تكتبها هكذا كما في الشكل لتعطي شكل جميل يسر الناظر
 واتمنى أن تجعلها رمز يونيكودي
وكنت أريد أن أسألك سؤال هل النون الخاصة بكلمة الدين في سورة الفاتحة موجود رمز يونيكود له ولو كام له ماهو رمزه

**Comment by Mos6720009** [comment]
وهل يمكنك اضافة شكل النون في  كلمة الدين في سورة الفاتحة وجعلها رمز يونيكودي

**Comment by khaledhosny** [comment]
> مثلا لو كنت تريد كتابة كلمة فيها لح أو لخ او لج تكتبها هكذا كما في الشكل لتعطي شكل جميل يسر الناظر

أقصد ما فائدتها مقارنة بشكلها الحالي في الخط:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/93914/192088871-ca381ec4-a651-4fdd-8878-6e3833477bf5.png">

فهذا خط طباعي حاسوبي وليس من أهدافه تضمين كل تنويعة من أشكال الحروف يكتبها الخطاطون.

>  وكنت أريد أن أسألك سؤال هل النون الخاصة بكلمة الدين في سورة الفاتحة موجود رمز يونيكود له ولو كام له ماهو رمزه

لا أفهم ما تقصده، النون هي النون، ليس لها إلا رمز واحد في يونيكود، ولا أعرف ما تعنيه بنون كلمة الدين، فشكل النون يعتمد على اختيارات الخطاط الذي خط المصحف، والمصاحف كثيرة.

**Comment by Mos6720009** [comment]
أقصد هل شكل النون في سورة الفاتحة كما في الصورة
![Uploading Screenshot_٢٠٢٢٠٩١١-١٧٥٧٠٧_Google.jpg…]()

**Comment by Mos6720009** [comment]
و لو استطعت اضافة شكل اللام ألف عذا
![Screenshot_٢٠٢٢٠٩٢٤-١٦٥٨٢٣_Chrome](https://user-images.githubusercontent.com/112905893/192104904-7221f193-46b6-44ba-9988-66f234d27748.jpg)

**Comment by khaledhosny** [comment]
هذا خط حاسوبي طباعي وليس خط خصاط، إذا كنت تريد محاكاة خط الخطاطين فيمكنك استخدام برمجيات مثل كليم https://kaleam.com

**Comment by Mos6720009** [comment]
وهل هو مجاني وكيف استخدمه

**Comment by khaledhosny** [comment]
كل التفاصيل موجودة على موقعهم، ولو بحثت على الإنترنت ستجد بدائل أخرى

**Comment by Mos6720009** [comment]
وهل هذا البرنامج يمكني منه التعديل على الخط الأميري

**Comment by Mos6720009** [comment]
اه طلب آخر هل يمكنك جعل الراء الثعبانية رمز يونيكودي

**Comment by Mos6720009** [comment]
أنا أقصد شكل النون في كلمة من وتكتب في بعض الكلمات في المصحف الأميري أو مصحف المدينة وربما قد أضيفها عن طريق كليم وسؤال هل كليم استطيع منه عمل خطوط والتعديل عليها
![Screenshot_٢٠٢٢٠٩٢٥-٢٢٢٨٠٤_Drive](https://user-images.githubusercontent.com/112905893/192163886-59880530-bbf9-49c4-92b1-0b70cde17504.jpg)
