### ISSUE TITLE
تداخل الأسطر

### ISSUE THREAD

**Issue by hatemibrahim1410** [khaledhosny/amiri-font#242]
السلام عليكم أستاذ خالد،
شكرًا لحضرتك على هذا الجهد في تصميم الخط ورعايته.

أعمل بالنسخة الأخيرة منه (0.900) وواجهت مشكلة هي قديمة لدي،
أنا أستخدم (مايكروسوفت وورد) كبرنامج أساسي للكتابة،
وعند الخط الأميري تتقارب الأسطر بحيث تختفي في السطر السابق، وتظهر بوضوح عند استخدام البرنامج، وعند طباعته لا تختفي الأسطر ولكتن تتداخل السطور كما هو موضح في الصورتين.
![pdf](https://user-images.githubusercontent.com/71362757/196170052-27ea25f7-3acf-461d-94d8-aa1125c85529.png)
![Word](https://user-images.githubusercontent.com/71362757/196170058-4349e4c0-c84b-419b-8f69-648777ba5623.png)

**Comment by khaledhosny** [comment]
جرب زيادة المسافة بين السطور.

**Comment by hatemibrahim1410** [comment]
نعم، بالفعل جربت زيادة المسافة بين الأسطر، وهذا نموذج لهذه الزيادة:-
![Screenshot_2](https://user-images.githubusercontent.com/71362757/197917751-f445b009-ff12-426d-aa4d-abbfd71429d1.png)

**Comment by khaledhosny** [comment]
المشكلة من البرنامج إذا.
