### ISSUE TITLE
Why does the rub el hizb look like an asterisk

### ISSUE THREAD

**Issue by amarz45** [khaledhosny/amiri-font#245]
The rub el hizb or Islamic star is a character that is used to divide the Quran in sections. It looks like this: ۞. However, on Amiri, it looks more like an asterisk (*).

**Amiri Quran:**

![](https://i.imgur.com/KrM7zE2.png)

**Scheherazade New:**

![](https://i.imgur.com/yXQfFn5.png)

Most Arabic fonts make it look the way Scheherazade New makes it look, and I think it looks a lot better that way. I am wondering why this font chooses to make it look more like an asterisk. Can you change it? If not, is there a way I can replace it myself?

**Comment by khaledhosny** [comment]
Amiri is based on the Bulaq Press types (مطبعة بولاق، المطبعة الأميرية) and the Azahar mushaf printed using these types (المصحف الأميري):

<img width="624" alt="image" src="https://user-images.githubusercontent.com/93914/204088315-5db2899a-78da-4c2e-88b5-3e12c9dca3dd.png">

It should be possible to add an alternate glyph for it, but I this point I’m preparing to freeze Amiri development and consider it done. Further development might happen at some point in the future, but it will be a different font.

**Comment by amarz45** [comment]
Okay, I switched to the [Kitab](https://github.com/quranacademy/kitab-font) font which looks similar but has what I want.
