### ISSUE TITLE
بخصوص اخر تحديث

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#248]
السلام عليكم هل معنى أن الخط الأميري بعد هذا التحديث سينتهي ولن يوجد شيء اسمه خط أميري أم سيتم تطوير خط تحت نفس الاسم أخبرني ماذا سيحديث

**Comment by khaledhosny** [comment]
يعني أن الخط الأميري سيبقى كما هو دون أن تغيير، لا بالسلب ولا بالإيجاب. في المستقبل قد أعمل على نسخة جديدة من الخط باسم مختلف تحل بعض المشاكل التي يصعب حلها في الخط الأميري على صورته الحالية.

**Comment by Mos6720009** [comment]
كيف ستكون النسخة الجديدة

**Comment by khaledhosny** [comment]
لم أفهم السؤال

**Comment by Mos6720009** [comment]
هل التغييرات فيها ستكون جوهرية وهل سيبقى نفس الاسم وهل سيكون خط نسخي
كل هذا الأسئلة جمعتها في سؤال واحد أجب عليها

**Comment by khaledhosny** [comment]
التغييرات في علم الغيب، لكن سيكون باسم مختلف وسيظل بنفس التصميم الأساسي.

**Comment by Mos6720009** [comment]
كيف بنفس التفاصيل وباسم مختلف

**Comment by Mos6720009** [comment]
بواقع خبرتك أخبرني عن البرنامج الذي صممت به الخط الأميري وأين تعلمت تصميم الخطوط لأني أريد أن أعدل عليه وأضع له تحديثات ارجو الرد لو سمحت

**Comment by khaledhosny** [comment]
صممت الأميري ببرنامج [فونتفورج](https://fontforge.org/en-US/) والنسخة الأخيرة ببرنامج [جليفز](https://glyphsapp.com/). علمت نفسي تصميم الخطوط.

**Comment by Mos6720009** [comment]
من أين تعلمت تصميمها
