### ISSUE TITLE
علامة الجنيه والقرش

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#249]
كيف تعمل تلك العلامتان لانهما لا يعملان

**Comment by khaledhosny** [comment]
هذه العلامات أضيفت حديثا إلى يونيكود لذا قد لا تدعمها كل البرامج، تعمل العلامتان مثلا علامة نهاية الآية، تكتب العلامة وبعدها الرقم.
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/93914/210151687-71763af6-9fc4-4d3b-85de-9e81e55f3c82.png">

**Comment by khaledhosny** [comment]
السعر فی المكتبات ࢐٢٥ احصل عليه الآن بسعر  ࢑١٠٠

**Comment by Mos6720009** [comment]
لا تعمل بهذا الشكل عندي
![لقطة الشاشة 2022-12-31 194620](https://user-images.githubusercontent.com/112905893/210151813-63db8ed7-47a4-4607-a58d-fb9c75ea8f55.png)
![لقطة الشاشة 2022-12-31 194905](https://user-images.githubusercontent.com/112905893/210151817-7045796b-6e6c-4999-8c39-1bc6312824a7.png)
