### ISSUE TITLE
خلل تقني

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#251]
حينما اكتب علامة الأية أو الحاشية أو سموت أو السنة لا تكتب بالرغم من الضغط على العلامات وهذه المشكلة حصلت في اخر تحديث ما الحل

**Comment by khaledhosny** [comment]
أحتاج تفاصيل أكثر عن البرنامج المستخدم، ونسخة من النص الذي جربته.

**Comment by Mos6720009** [comment]
[مستند Microsoft Word جديد (8).pdf](https://github.com/aliftype/amiri/files/10420675/Microsoft.Word.8.pdf)
اسم البرنامج مايكوسوفت 2016

**Comment by khaledhosny** [comment]
أحتاج ملف وورد نفسه.

**Comment by khaledhosny** [comment]
كما يجب أن تكتب العلامة أولا ثم الأرقام.

**Comment by Mos6720009** [comment]
هذا نص كتبته عن الخط الاميري
[مستند Microsoft Word جديد.pdf](https://github.com/aliftype/amiri/files/10425858/Microsoft.Word.pdf)

**Comment by Mos6720009** [comment]
والعلامات لا تعمل لا أعرف لماذا بالرغم من عملها في اصدارات سابقة

**Comment by khaledhosny** [comment]
أخى العزيز أحتاج ملف  docx وليس ملف pdf

**Comment by Mos6720009** [comment]
ها هو 
ارسلت شكوى في خط عارف رقعة ارجو الرد عليها
[مستند Microsoft Word جديد.docx](https://github.com/aliftype/amiri/files/10427492/Microsoft.Word.docx)

**Comment by khaledhosny** [comment]
هذه مشكلة في ميكروسوفت أوفيس، عندما أنسخ النص لملف جديد كل شيء يعمب كما ينبغي عندي على ليبر أوفيس:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/93914/212734816-0c9968b9-a54c-4b97-b577-3033781f51d0.png">

[Untitled 2.docx](https://github.com/aliftype/amiri/files/10427985/Untitled.2.docx)
