### ISSUE TITLE
تباعد وتداخل للحروف عند استخدام ليبر اوفيس 7.3.7.2

### ISSUE THREAD

**Issue by muhammed-ahmad** [khaledhosny/amiri-font#253]
السلام عليكم:
عند استخدام ليبر اوفيس 7.3.7.2 وجدت تباعد وتداخل لبعض الحروف
هذا في النسخه الاخيره "1.000" أما النسخه القديمه "2019" فلا يوجد بها ذلك.
وجزاك الله خيرا على هذا الخط الأكثر من رائع.

**Comment by khaledhosny** [comment]
النسخة الأخيرة من الخط تحتاج ليبر أوفيس ٧,٥ أو أحدث، إذا كنت تستخدم نسخة أقدم من ليبر أوفيس فيستحسن استخدام النسخة القديمة من الخط.

**Comment by muhammed-ahmad** [comment]
حسنا, جزاك الله خيرا
