### ISSUE TITLE
بخصوص الخط الأميري

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#254]
لماذا تم تجميد الخط الأميري برغم عدم توفر بعض محارفه وهل يتم ذلك عن طريق تصميم خط جديد

وشيء أخر لقد أرسلت شكوى في عارف رقعة ولم يتم الرد عليها وعنوانها السلام عليكم

**Comment by Mos6720009** [comment]
أقصد هل يتم تعديل الخط عن طريق خط جديد

**Comment by khaledhosny** [comment]
https://github.com/aliftype/amiri/blob/main/README-Arabic.md#%D9%88%D8%B6%D8%B9-%D8%A7%D9%84%D8%AA%D8%B7%D9%88%D9%8A%D8%B1
