### ISSUE TITLE
 كيف أكتب بالشكل الثاني للهاء النهائية أو التاء المربوطة 

### ISSUE THREAD

**Issue by Mos6720009** [khaledhosny/amiri-font#256]
السلام عليكم ورحمة الله وبركاته، هذا الشكل للهاء النهائية والتاء المربوطة الذي موجود في الصورة
![Screenshot_٢٠٢٣٠٥٠١-٢٠٣٧٤٩_Chrome](https://user-images.githubusercontent.com/112905893/235500180-bdda2daf-a919-48b3-9047-3f3a37b7b0cc.jpg)
 كيف أكتب مع العلم أنه حينما أستدعي هذا الشكل من يونيكود يكتب منفصل فكيف أكتبه مشبوكًا بحرف لو كان تاء مربوطة أو هاء مربوطة 
ونآسف على الإطالة

**Comment by khaledhosny** [comment]
ہ U+06C1 و ۃ U+06C3


مثال: إلہ وآلۃ  
<img width="186" alt="image" src="https://user-images.githubusercontent.com/93914/235517552-0dcce7c5-01de-4bda-b3ae-7e1ce1784c2c.png">
