### ISSUE TITLE
Diacritics placement in InDesign CS6

### ISSUE THREAD

**Issue by ad102030** [khaledhosny/amiri-font#260]
Please see attached screen shots for use of Amir Quran in InDesign CS6 on Windows 11. Using Amir Regular and the recommended Quranic text (https://github.com/aliftype/quran-data/tree/main/quran) did not produce different results.

Image 1 shows default Opentype diacritic positioning. Image 2 shows "tight" diacritic positioning.

![Amiri-Quran-screenshot1](https://github.com/aliftype/amiri/assets/27583305/5a93ee7d-dadf-4a54-a9aa-b1506cb26736)

![Amiri-Quran-screenshot-normal-diacritics](https://github.com/aliftype/amiri/assets/27583305/c39e9828-27b0-49a9-b9f7-854bd5c5e48c)

**Comment by khaledhosny** [comment]
I have no idea what InDesign is doing here, the font works fine in every other application I can test, including other Adobe apps like Photoshop and Illustrator.
