### ISSUE TITLE
Numbering periods in MS Word

### ISSUE THREAD

**Issue by rb-rb** [khaledhosny/amiri-font#262]
Amiri uses different periods for numbering lists and inline text. This could be an MS Word issue but I don't have it with other fonts. Also cannot solve it by changing anything in the list options. Problem only occurs with the period (.)

![Screenshot 2023-10-16 122631](https://github.com/aliftype/amiri/assets/148060868/6ce7f487-704a-4752-ac92-dd091a60a63a)

Left is the numbering list, right is the inline text.

**Comment by khaledhosny** [comment]
This is a word bug. Amiri’s default period (the diamond-like one) is designed for Arabic, and there is alternate rounded one for Latin and should be activated by default for Latin script. 

It seems that Word is not activating the Latin-specific alternate for list numbers.
