### ISSUE TITLE
End of Ayah and LuaLaTeX

### ISSUE THREAD

**Issue by ralessi** [khaledhosny/amiri-font#263]
This issue may not be related to Amiri, or to Amiri only, or even to Amiri at all, but I thought this might be the best place to ask.

Compiling with LuaLaTeX what follows:—

```latex
\documentclass{article}

\usepackage{fontspec}
\defaultfontfeatures{Renderer=Harfbuzz}
\newfontfamily\amiri{Amiri}[Script=Arabic,Language=Arabic]
\newfontfamily\scheherazade{Scheherazade New}[Script=Arabic]
\newfontfamily\freeserif{FreeSerif}[Script=Arabic]

\begin{document}

Amiri (1.0, CTAN):
\bgroup
\textdir TRT
\amiri
رقم الآية
١۝
\egroup

Scheherazade New 4.0:
\bgroup
\textdir TRT
\scheherazade
رقم الآية
١۝
\egroup

FreeSerif (CTAN):
\bgroup
\textdir TRT
\freeserif
رقم الآية
١۝
\egroup

\end{document}
```

Produces this:
![ayah_000](https://github.com/aliftype/amiri/assets/389498/34bc8f56-c69e-4e58-81aa-b6f99dab6edf)

Scheherazade works, but neither FreeSerif nor Amiri 1.0, which is the font that arabluatex uses by default, does.

I tried other versions of Amiri and I can say that Amiri 0.117 is the last version that used to work.

But since the problem also appears with other fonts such as FreeSerif, do you have any idea where it might be coming from?

**Comment by khaledhosny** [comment]
There are two issues in your input:
* End of Ayah sign and the numbers should be LTR, so you need to use `\textdir TLT` for them.
* The number should come after the sign, so your input should be `۝١` not `١۝`.

Fixing both issues gives the correct rendering:
```tex
\bgroup
\textdir TRT
\amiri
رقم الآية
{\textdir TLT ۝١}
\egroup
```
<img width="455" alt="image" src="https://github.com/aliftype/amiri/assets/93914/c03f2264-d3f8-4b53-b490-9561b722b4bc">

**Comment by ralessi** [comment]
My mistake.  Excellent, thank you very much! (And sorry for the noise.)
