### ISSUE TITLE
دعم الكشيدة التلقائية في ضبط النص

### ISSUE THREAD

**Issue by Aisiabn** [khaledhosny/amiri-font#271]
الخط لا يدعم خصائص ضبط النص (كشيدة صغيرة /متوسطة /كبيرة)، والحروف تنفصل عن بعضها بدلا من تمدد الكشيدات تلقائيا لوصل الحروف

**Comment by khaledhosny** [comment]
انظر https://github.com/aliftype/amiri/issues/201

**Comment by Aisiabn** [comment]
هل يمكن للخط دعم ligatures للتغلب على هذه المشكلة؟

في الثلاثاء، 16 يوليو 2024, 17:31 خالد حسني (Khaled Hosny) <
***@***.***> كتب:

**Comment by khaledhosny** [comment]
هذا يتطلب بناء الخط كله من جديد، وإضافة عشرات الآلاف من المحارف للخط. مثلا ”بي“ (باء ياء) وحدها تحتاج ٦٣٠ محرفا جديدا بهذه الطريقة، وهذه علاقة واحدة من أكثر من ١٥٠ علاقة يدعمها الخط.

**Comment by Aisiabn** [comment]
تمام.. اتضحت الفكرة
عندي فكرة أريد عملها لو سمحتم
أريد توضيح كيفية تفعيل خاصية الكشيدة التلقائية في برنامج font creator (أو
إرسال نسخة من أوزان الخط مفعل فيها هذه الخاصية) ثم أعمل فيها على حذف كافة
تراكيب الحروف وإبقاء الحروف المفردة بحالاتها الأربعة (أول ووسط وآخر الكلام
والمفردة) وإضافة محرف (لا) بهمزاته وحالاته بحيث تعمل الكشيدة التلقائية بدون
مشاكل (أعلم أنه سينقص كثيرا من الحالات المميزة للحروف، لكن مجرد تجربة أسهل
من استحداث محارف جديدة)
فما رأيكم؟


في الأربعاء، 17 يوليو 2024, 00:16 خالد حسني (Khaled Hosny) <
***@***.***> كتب:

**Comment by khaledhosny** [comment]
في هذه الحالة يمكنك أن تستخدم خطا آخر لا يحتوي أيا من هذه التراكيب، مثل https://software.sil.org/scheherazade/download/. أما عن فونت كريوتر، فلم أستخدمه من قبل.

**Comment by Aisiabn** [comment]
خط شهرزاد أستخدمه بالفعل وهو جيد..
هل ترشحون برنامج آخر ترونه أفضل من font creator؟

وأرجو منكم إرشادي إلى كيفية تفعيل الكشيدا وأنا سأحاول مع نفسي في نسخة من
الخط الأميري.. مجرد محاولة.. وربنا ييسر
ولكم جزيل الشكر

في الأربعاء، 17 يوليو 2024, 11:06 خالد حسني (Khaled Hosny) <
***@***.***> كتب:

**Comment by khaledhosny** [comment]
أستخدم برنامج جليفز وهو لا يعمل إلا على ماك. إذا حذف كل التراكيب من الخط، فما يبقى لن يختلف كثيرا عن شهرزاد، لذا لا أرى ما الفائدة من المحاولة. ما يميز أميري عن غيره من الخطوط النسخية هو ثرائه في التراكيب. يمكنك أن تجرب حزمة ليبرأوفيس المكتبية، فالكشيدة التلقائية فيها تعمل مع الخط الأميري.

**Comment by Aisiabn** [comment]
سأجربه على ليبرواوفيس.. أنا بالفعل أستخدمه منذ مدة بجانب حزمة أوفيس، لكن
يخطر ببالي التجربة عليه.. شكرا جزيلا على هذه الفائدة 🌹

في الأربعاء، 17 يوليو 2024, 16:08 خالد حسني (Khaled Hosny) <
***@***.***> كتب:

**Comment by Aisiabn** [comment]
السلام عليكم ورحمة الله
كنت كلمتكم قريبا بخصوص تفعيل الكشيدا للخط الأميري
واطلعت على ردكم
فقمت بعمل ما في الخط: أن قمت بتعطيل الاستبدالات الداخلية التي كانت تظهر
مشاكل في الكشيدا التلقائية، وعمل الخط بشكل جيد، سوى أن (لا) لا تعمل، فقمت
بعمد جدول استبدال خاص بها، ولم يعمل رغم انه مكتوب بشكل سليم، فهل تسمحون
بإرسال نسخة من الخط لكم للاطلاع عليها ومساعدتي في تشغيلها بشكل سليم؟ إن
تكرمتم
ولكم جزيل الشكر
