### ISSUE TITLE
Font encoding is mangled/Not-Unicode for PDFs generated by *TeX

### ISSUE THREAD

**Issue by faresbakhit** [khaledhosny/amiri-font#272]
A PDF compiled with XeTex/LuaTeX with babel/polyglossia will have the text **inside** the PDF (not the rendered text, the raw text) written in a Non-Unicode encoding, thus not readable to screen readers for visually impaired people.

This is not a TeX engine or multilingual support package bug (please correct me if I'm wrong), I have tested and replicated the same behavior on (XeTex-babel, XeTeX-polyglossia, LuaTeX-babel, LuaTeX-polyglossia) but using another Arabic font (e.g. [Scheherazade New](https://software.sil.org/scheherazade/)) yields correct results (although not in all cases). Here is a minimal reproducible example I have tested on my XeTex/babel installation (I've confirmed the others on overleaf):

<details>

<summary>XeTeX/babel source file:</summary>

```tex
% test.tex

\documentclass{article}

\usepackage[bidi=default]{babel}
\babelprovide[import, main]{arabic}

% Amiri

\babelfont{rm}[
  Language = Arabic,
  Path = fonts/Amiri/,
  Extension = .ttf,
  UprightFont = Amiri-Regular,
  BoldFont = Amiri-Bold,
  ItalicFont = Amiri-Italic,
  BoldItalicFont = Amiri-BoldItalic,
]{Amiri}


% Scheherazade New

% \babelfont{rm}[
%   Language = Arabic,
%   Path = fonts/ScheherazadeNew/,
%   Extension = .ttf,
%   UprightFont = ScheherazadeNew-Regular,
%   BoldFont = ScheherazadeNew-Bold,
% ]{Scheherazade New}

\begin{document}
اشترى جحا عشرة حمير فركب واحداً منها وساق تسعة أمامه، ثم عدّ الحمير ونسي الحمار
الذي يركبه فوجدها تسعة، فنزل عن الحمار وعدها فوجدها عشرة، فركب مرة ثانية وعدها
فوجدها تسعة، ثم نزل وعدها فوجدها عشرة وأعاد ذلك مراراً فقال: أنا أمشي وأربح
حماراً خير من أن أركب ويذهب مني حمار فمشى خلف الحمير حتى وصل إلى منزله.
\end{document}
```

</details>

## How to test

This behavior can be tested without a screen-reader by copying the text on a PDF document viewer (I have tested this on zathura-mupdf and the Chromium PDF viewer) or better, using [Poppler](https://poppler.freedesktop.org/)'s utility `pdftotext` as demonstrated below:

<details>

<summary>With the Amiri font used:</summary>

```sh
13:58:34 ~/test
$ xelatex test.tex
This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
...
Output written on test.pdf (1 page).

13:58:37 ~/test
$ pdftotext test.pdf /dev/stdout
ﺍ‬
،‬‬

ﻯ‬
ﻝ‬

ﺓ ﻭﺃ ﺩ ﺫ‬
ﺇ‬
ﻭ‬

ﺓ‬
ﺍ ﺭﻭ‬

ﺍﺭﺍ ً‬
.‬‬

ﻭﺍ‬
ﻝ‪ :‬ﺃ ﺃ‬

ﺍً‬

ﺓ‪،‬‬

ﻭﺃﺭ‬

ﻭ ﻕ‬

ﺓ‬

ﺭﺍ ً‬

1‬‬

ﺃ‬

،‬‬
ﻭ‬

ﺃﻥ ﺃﺭ‬

ﻭ‬

ﺍ‬
ﻭ‬

ﺍ ﺭﺍ ﻱ‬
ﻝﻭ‬
،‬‬
ﺭ‬

ﺍ‬


```
</details>

<details>

<summary>With the Scheherazade New font used:</summary>

This is not free of issues, but it gets almost all of the text right. (e.g. `ا ٕلى` is encoded as 4 Unicode character)

```
13:58:41 ~/test
$ xelatex test.tex
This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
...
Output written on test.pdf (1 page).

13:58:55 ~/test
$ pdftotext test.pdf /dev/stdout
اشترى جحا عشرة حمير فركب واحداً منها وساق تسعة أمامه‪ ،‬ثم ع ّد الحمير ونسي الحمار الذي‬
يركبه فوجدها تسعة‪ ،‬فنزل عن الحمار وعدها فوجدها عشرة‪ ،‬فركب مرة ثانية وعدها فوجدها تسعة‪ ،‬ثم‬
نزل وعدها فوجدها عشرة وأعاد ذلك مراراً فقال‪ :‬أنا أمشي وأربح حماراً خير من أن أركب ويذهب مني‬
حمار فمشى خلف الحمير حتى وصل ا ٕلى منزله‪.‬‬

1‬‬


```
</details>

---

I'm no expert on how a font maps its glyphs into Unicode glyphs moreover how a *TeX engine/the PDF spec embed this data in a compiled file, so please take this "tests" with a grain of salt.

**Comment by faresbakhit** [comment]
Compiling [Documentation-Arabic.tex](https://github.com/aliftype/amiri/blob/745aaf546d15ace0ba2588354a225724204c931c/documentation/Documentation-Arabic.tex) with LuaLaTeX yields disconnected characters for me:

```
‫ﻡقﺩﻡﺓ‬
‫الﺥط الﺃﻡيﺭي ﺥط نﺱﺥي ﻡوجه لطﺏاﻉﺓ الـﻙﺕﺏ و النﺹوص الطو يلﺓ‪ ،‬و هو إﺡياء و ﻡﺡاﻙاة‬
‫للﺥط الطﺏاﻉي الجﻡيل الﺫي ﺕﻡيﺯت ﺏه ﻡطﺏﻉﺓ ﺏولﺍق ﻡنﺫ أواﺉل القﺭن الﻉشﺭ ين‪.‬‬
‫يﺕﻡيﺯ ﺥط الﻡطاﺏع الﺃﻡيﺭ يﺓ ﺏجﻡاليﺕه و ﻡﺭاﻉاﺕه لﻑن الﺥط الﻉﺭ ﺏي‪ ،‬ﺏﺃﺱلوب نﺱﺥي جﻡيل‪ ،‬و
```

But piping the [Documentation-Arabic.pdf](https://github.com/aliftype/amiri/blob/745aaf546d15ace0ba2588354a225724204c931c/documentation/Documentation-Arabic.pdf) provided in the repo into `pdftotext` yields perfect 1:1 mapping to the Unicode text. I'm not sure what is wrong with my setup.

**Comment by khaledhosny** [comment]
I don’t know either. But anyway, this project is frozen, and I do not intend to make any more changes, so even if I can figure out a way to make the font work better with some PDF generators, I do not have the capacity nor the will to implement such change.

**Comment by faresbakhit** [comment]
Understandable. I guess - against my earlier judgement - that the breakage is not on the font's side, but rather the TeX engines since the project has been frozen for quite a while, and the TeX engines used to produce correct results.

Thanks for your time, and this beautiful typeface.
